### ISSUE TITLE
Running on the mac; some issues

### ISSUE THREAD

**Issue by gvdhoven** [YIO-Remote/remote-software#148] opened 2019-05-22 09:28 UTC
```
11:22:30: Starting /Documents/GitHub/yio-remote/software/build-remote-Desktop_Qt_5_12_3_clang_64bit-Debug/remote.app/Contents/MacOS/remote ...
QML debugging is enabled. Only use this in a safe environment.
QQmlComponent: Component is not ready
qml: Websocket connection closed: false
qml: Error: Socket is not connected
qml: Websocket connection error: false
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qrc:/components/light/Button.qml:18:5: Unable to assign [undefined] to int
qml: Update error: 404
qml: Reconnecting...
qml: Websocket connection closed: false
qml: Error: Socket is not connected
qml: Websocket connection error: false
qrc:/main.qml:55: TypeError: Property 'getVoltage' of object BQ27441(0x7fe10a592320) is not a function
qml: Reconnecting...
qml: Websocket connection closed: false
qml: Error: Socket is not connected
qml: Websocket connection error: false
qml: Reconnecting...
qml: Websocket connection closed: false
qml: Error: Socket is not connected
qml: Websocket connection error: false
11:22:41: /Documents/GitHub/yio-remote/software/build-remote-Desktop_Qt_5_12_3_clang_64bit-Debug/remote.app/Contents/MacOS/remote exited with code 0
```

2 issues;
1) When booting, wait until connected to load the devices (probably solves all the `Unable to assign [undefined] to int` issues). This has UI impact; preferably wait with showing ANY ui until 'connected'. As reported to Marton via Discord in PM.
2) Fix battery level on mac to report a fixed value

**Comment by gvdhoven** [comment] 2019-05-22 10:09
battery level seems to be fixed now, issue '1' remains.

**Comment by martonborzak** [comment] 2019-05-26 12:02
I have to revert all your changes, because it generates a lot of errors on the actual hardware. You cannot get values out of the battery fuel gauge before it's initialised and so on.

**Comment by martonborzak** [comment] 2019-05-26 13:16
@Webunity the issue is caused by having empty configuration entries in `config.json`. I removed the empty home assistant and homey config options. Everything works. Closing the issue.

**Closed as completed by martonborzak** 2019-05-26 13:16 UTC
Labels: bug, medium priority
